City-of-Helsinki/drupal-helfi-form-tool

public/modules/custom/form_tool_webform_components/form_tool_profile_data/src/Element/FormToolProfileData.php

* Add check for profile data module for null.
* Checkout the branch and run make commands.
* `git checkout origin LOM-X_fix_for_null_on_profile_data`
* `make drush-cr`

LOM-X Fix for WSOD on when profile data is not available

---

composer.json
composer.lock
conf/cmi/field.storage.paragraph.field_list_of_links_design.yml
conf/cmi/language/fi/field.storage.paragraph.field_list_of_links_design.yml

* Updated codebase to latest versions
* Checkout the branch and run make commands.
* `git checkout origin LOM-X_update_codebase`
* `make drush-cr`

LOM-X Updated codebase to latest versions

---

conf/cmi/language/fi/field.field.node.article.field_content.yml
conf/cmi/language/fi/field.field.node.article.field_lead.yml
conf/cmi/language/fi/paragraphs.paragraphs_type.remote_video.yml
conf/cmi/language/fi/views.view.scheduler_scheduled_content.yml
conf/cmi/language/sv/responsive_image.styles.original.yml
conf/cmi/language/sv/views.view.user_admin_people.yml
conf/cmi/update.settings.yml

1. Checkout this branch
2. Run `make drush-cim && make drush-cr`
3. Check that the site still works correctly. These are just some files that were not included to the configurations but after running `drush locale:check; drush locale:update; drush cr`

LOM-X Missing translations and configurations

---

lomake-run-robot-tests.yml

yml file added

---

azure-pipelines-dev.yml
azure-pipelines-staging.yml
azure-pipelines-test.yml

Update deployemnt triggers to prepare for production launch.
* `make fresh`

Update azure triggers.

---

lomake-run-robot-tests.yml
test/resources/variables/common-Variables.robot
test/resources/variables/lomake-Variables.robot
test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot
test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot

new test file and fixes

---

lomake-run-robot-tests.yml
test/resources/variables/lomake-Variables.robot
test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot
test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot
test/tests/lomake-direct-lomake-url.robot

new tests added

---

test/resources/keywords/lomake-Keywords.robot
test/resources/variables/lomake-Variables.robot
test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot
test/tests/lomake-direct-lomake-url.robot
test/tests/lomake-direct-url-and-content-in-mail.robot

new test added

---

PROD-lomake-test-set.yml
SMOKE-lomake-test-set.yml
test/tests/PROD-lomake-test-set.robot
test/tests/SMOKE-lomake-test-set.robot

test: LOM-324: Smoke and prod test set added

---

lomake-run-robot-tests.yml
scheduled-test-env-browsers-run.yml
test/resources/keywords/lomake-Keywords.robot
test/resources/variables/lomake-Variables.robot
test/tests/PROD-lomake-test-set.robot
test/tests/SMOKE-lomake-test-set.robot
test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot
test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot
test/tests/lomake-direct-lomake-url.robot
test/tests/lomake-direct-url-and-content-in-mail.robot

test: LOM-351: Test env update

---

lomake-run-robot-tests.yml
test/resources/variables/lomake-Variables.robot
test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot
test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot

test: LOM-XX: Testing new features

---

composer.lock

Update helsinki profiili module to new version to support api token endpoint in environment variable.
* Helsinki profiili to 0.9.4

fix: LOM-398: Update helsinki profiili module

---

composer.lock

Another version bump for hp

---

lomake-run-robot-tests.yml
test/resources/keywords/lomake-Keywords.robot

- default env changed from dev to test
- "Capture Page Screenshot" keyword debugging
* `make fresh`

test: fix default env

---

.gitignore
SMOKE-lomake-test-set.yml
lomake-run-robot-tests.yml
test/resources/keywords/lomake-Keywords.robot
test/resources/variables/lomake-Variables.robot
test/tests/SMOKE-lomake-test-set.robot
test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot

LOM-409
- Locator fixed
- .gitignore updated
- folder fix SMOKE-lomake-test-set.yml
- logit folder added to lomake-run-robot-tests.yml
- Some lomake-run-robot-tests.yml
- Admin test variables added
* `make fresh`

test: LOM-409 locator changed

---

lomake-run-robot-tests.yml
test/tests/PROD-lomake-test-set.robot
test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot
test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot
test/tests/lomake-direct-lomake-url.robot
test/tests/lomake-direct-url-and-content-in-mail.robot

- Sourcefolder url fixed
- Correct tags added to robot tests files
* `make fresh`

test: fixed url LOM-409

---

test/tests/lomake-direct-lomake-url.robot

Changed something to test new pipeline settings
* `make fresh`

test: LOM-406 pipeline trigger test

---

test/tests/lomake-direct-lomake-url.robot

test: LOM-406 pipeline trigger test again

---

README.md

* Update README to include mailhog configurations.

docs: Add information about mailhog configuration

---

SMOKE-lomake-test-set.yml

fix: LOM-325 fixed log urls

---

test/tests/SMOKE-lomake-test-set.robot

Logout step fixed
* `make fresh`

fix: LOM-325 fixed logout

---

lomake-run-robot-tests.yml
test/tests/lomake-direct-lomake-url.robot

Debugging why test fails in azure
* `make fresh`

fix: LOM-382 debugging why test fails

---

composer.json
composer.lock
conf/cmi/webform.webform.todistusjaljennospyynto_tilaus.yml
public/modules/custom/form_tool_webform_components/form_tool_contact_info/src/Plugin/WebformElement/FormToolContactInfo.php

* Added phone number to be seen in postiennakko delivery method
* `git checkout feature/LOM-451-phone-number`
* `make fresh`
[LOM-451]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: LOM-451: Added phone number to be seen in postiennakko delivery method

---

conf/cmi/webform.webform.todistusjaljennospyynto_tilaus.yml

fix: LOM-XX: Privacy policy typo

---

.env
test/resources/keywords/lomake-Keywords.robot
tools/make/project/robot.mk

Some ROBOT_OPTIONS lines removed from robot.mk file
[LOM-469]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: LOM-469: robotoptions lines removed

---

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme

Add noindex robots meta tag
* `git checkout LOM-463-no-index`
* `make fresh`
[LOM-463]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LOM-463: Add noindex tag

---

conf/cmi/smtp.settings.yml

* Update from address and name
* `git checkout LOM-465-smtp-settings`
* `make fresh`
[LOM-465]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LOM-465: Update smtp sender and from info

---

.env
test/resources/keywords/lomake-Keywords.robot
test/resources/variables/lomake-Variables.robot
tools/make/project/robot.mk

Fixed rekisteriseloste locator
[LOM-471]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix  lom 471  rekisteriseloste locator changed

---

.env
CHANGELOG.md
composer.json
conf/cmi/smtp.settings.yml
public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
test/resources/keywords/lomake-Keywords.robot
test/resources/variables/lomake-Variables.robot
tools/make/project/robot.mk

Release 2023.7

---

public/themes/custom/hdbt_subtheme/templates/field/field--node--webform--webform.html.twig
public/themes/custom/hdbt_subtheme/translations/fi.po
public/themes/custom/hdbt_subtheme/translations/sv.po

* Added notification about asterisk
* `git checkout feature/LOM-480-asterisk-notification`
* `make fresh`
[LOM-480]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: LOM-480: add asterisk notification

---

composer.lock

Reverts City-of-Helsinki/drupal-helfi-form-tool#190

Revert "Automatic update"

---

conf/cmi/language/sv/webform.webform.todistusjaljennospyynto_tilaus.yml
public/modules/custom/form_tool_share/src/Controller/FormCompletionController.php

fix: LOM-514: Fix banner & other translations

---

public/themes/custom/hdbt_subtheme/src/scss/06_components/layout/_dialog.scss

LOM-516: Hide english translation link

---

.gitignore
lomake-run-robot-tests.yml
test/resources/variables/lomake-Variables.robot
test/tests/SMOKE-lomake-test-set.robot
test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot
test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot
test/tests/lomake-direct-lomake-url.robot
test/tests/lomake-direct-url-and-content-in-mail.robot

Selenium version changed to 4.9.1
[LOM-520]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: LOM-520: Selenium version changed

---

.gitignore
lomake-run-robot-tests.yml
test/resources/keywords/lomake-Keywords.robot
test/resources/variables/lomake-Variables.robot
test/tests/SMOKE-lomake-test-set.robot
test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot
test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot
test/tests/lomake-direct-lomake-url.robot
test/tests/lomake-direct-url-and-content-in-mail.robot

Sleep added when open browser
[LOM-521]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: LOM-521: Sleep added when open browser

---

conf/cmi/smtp.settings.yml

https://helsinkisolutionoffice.atlassian.net/browse/PLAENH-1220 updates the email service. This will conform to that.
[LOM-531]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LOM-531: Update smtp server to relay.hel.fi

---

composer.lock
conf/cmi/helfi_helsinki_profiili.settings.yml

LOM-539: Update HP module
