- conf/cmi/update.settings.yml
- conf/cmi/user.role.admin.yml
- conf/cmi/user.role.authenticated.yml
- conf/cmi/user.role.content_producer.yml
- conf/cmi/user.role.editor.yml
- conf/cmi/user.role.helsinkiprofiili_heikko.yml
- conf/cmi/user.role.helsinkiprofiili_vahva.yml
- conf/cmi/user.role.read_only.yml
- conf/cmi/user.role.verkkolomake_admin.yml
- conf/cmi/user.role.verkkolomake_hallinnoija.yml
- conf/cmi/user.role.verkkolomake_kasittelija.yml
* Updated the editor and admin role permissions so that these users can create, translate, edit and remove the webform-nodes.
* Checkout the branch and run make commands.
* `git checkout origin LOM-294_webform_node_type_permissions`
* `make drush-cim && make drush-cr`
> LOM-294 Updated permissions so that admin and editor have correct ones

- composer.lock
1. Checkout this branch
2. Run `composer install`
3. Run `make drush-cr`
4. Check that the hdbt has been updated to latest version (https://hel-fi-form-tool.docker.so/fi/admin/debug) and that layout looks good.
> LOM-X updated hdbt to latest version

- composer.json
- public/modules/custom/form_tool_webform_parameters/form_tool_webform_parameters.module
- Added patch to fix compatibility issues with webform and php 8.1
- Added custom node form validation where the webform form code field can be populated based on chosen webform.
- `git checkout LOM-284_hide_form_code`
- `composer install`
- `drush cr`
- Go to add or edit a webform node type
- Select webform and save the node
- Check that the node gets url alias based on the selected webform
- Check also translations
> LOM-284 Hide form code

- conf/cmi/eu_cookie_compliance.settings.yml
- conf/cmi/language/fi/eu_cookie_compliance.settings.yml
- conf/cmi/language/sv/eu_cookie_compliance.settings.yml
* Fixed button text on cookie information and settings page.
* Checkout the branch and run make commands.
* `git checkout origin LOM-269_updated_cookie_banner_settings`
* `make drush-cim && make drush-cr`
[LOM-269]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-269 Updated the incorrect text from cookie settings page

- public/modules/custom/form_tool_share/form_tool_share.routing.yml
- public/modules/custom/form_tool_share/translations/fi.po
- public/modules/custom/form_tool_share/translations/sv.po
* Fixed one titles language on routing file.
* Added missing translations.
* `git checkout LOM-273_missing_translations
* `make drush-cim && make drush-cr`
* `make shell`
* `drush locale:check; drush locale:update; drush cr`
[LOM-273]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-273 Fixed one title on routing file and added translations

- public/modules/custom/form_tool_webform_parameters/form_tool_webform_parameters.module
* Fixed typo in postal address in third party settings
* `git checkout LOM-344-asetukset-toimitusosoite`
* `make fresh`
[LOM-344]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-344: fix typo in postal address

- public/modules/custom/form_tool_webform_components/form_tool_profile_data/src/Element/FormToolProfileData.php
- public/modules/custom/form_tool_webform_components/form_tool_profile_data/translations/fi/fi.po
- public/modules/custom/form_tool_webform_components/form_tool_profile_data/translations/sv/sv.po
* Helsinki-profiili now directs to the correct place
* `make fresh`
* Add a line to your local settings: `putenv('HELSINKI_PROFIILI_URI=https://profiili.test.hel.ninja/login');`
[LOM-348]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-348: helsinkiprofiili-linkki

- public/modules/custom/webform_formtool_handler/templates/submission-print.html.twig
- public/modules/custom/webform_formtool_handler/translations/fi/fi.po
- public/modules/custom/webform_formtool_handler/translations/sv/sv.po
* Since the Seurantasivu is only for the one MVP form and the stuff in the esitietolomake is not used anywhere else as it stands, the texts on the page can be set by hardcoding. The address and the toimiala are now printed correctly on the seurantasivu.
* `git checkout LOM-356-address-to-seurantasivu`
* `make fresh`
[LOM-356]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-356: hardcoding for MVP as this page is never seen again after this.

- composer.json
- composer.lock
Our authentications did not work when our staging environment is named staging, when all others are named stage. This maps those.
* Lari fixed this with api base update.
[LOM-398]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-398: Support naming convention staging

- public/modules/custom/form_tool_webform_parameters/form_tool_webform_parameters.module
Privacy policy link is again in the correct location
* Moved the privacy policy link (and wrapper) to the correct place, both in the order of the form (before the submit button) and the code (inside the elements array)
* `git checkout feature/LOM-397-form-submit-button-place`
* `make fresh`
[LOM-397]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-397: change location of privacy policy link

- public/modules/custom/form_tool_webform_components/form_tool_profile_data/src/Element/FormToolProfileData.php
* Changed validator to allow non-international number format
* `feature/LOM-376-phone-validator-fix`
* `make fresh`
[LOM-376]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-376: Fix phone validator to allow non-international format

- public/modules/custom/form_tool_webform_parameters/form_tool_webform_parameters.module
AC:
* Sanity checkattu elementin olemassa olo
* Virheviestit poistuneet
* Moved the three lines of code (that move the submit button to the bottom of the webforem) to be:
* Inside the 'if' that checks that it only happens in webform forms
* Inside a new if that checks there is an 'elements' array key in form array (even if this should always be true with webform forms) 
* `git checkout feature/LOM-404-warnings-on-forms`
* `make fresh`
> fix: LOM-404: sanity check for element array item in webform

- composer.json
- composer.lock
- conf/cmi/core.extension.yml
- public/modules/custom/form_tool_auditlog/form_tool_auditlog.info.yml
- public/modules/custom/form_tool_auditlog/form_tool_auditlog.module
- public/modules/custom/form_tool_auditlog/form_tool_auditlog.services.yml
- public/modules/custom/form_tool_auditlog/src/Event/UserPresaveEvent.php
- public/modules/custom/form_tool_auditlog/src/EventSubscriber/AuditLogEventSubscriber.php
- public/modules/custom/form_tool_auditlog/src/EventSubscriber/SubmissionViewSubscriber.php
- public/modules/custom/form_tool_auditlog/src/EventSubscriber/UserPresaveSubscriber.php
- public/modules/custom/form_tool_auditlog/src/EventSubscriber/WebformSubmissionSubscriber.php
- public/modules/custom/form_tool_share/src/Controller/FormToolSubmissionController.php
- public/modules/custom/form_tool_share/src/Event/SubmissionViewEvent.php
- public/modules/custom/webform_formtool_handler/src/Event/WebformSubmissionEvent.php
- public/modules/custom/webform_formtool_handler/src/Plugin/WebformHandler/FormToolWebformHandler.php
* Installed helfi_audit_log module
* Configured events based documentation
* `git checkout feature/LOM-352-audit-logging`
* `make fresh`
[LOM-352]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: LOM-352: Installed audit log module. Configuring audit log events

- composer.json
- composer.lock
- public/modules/custom/helfi_gdpr_api/src/Controller/HelfiGdprApiController.php
ATV used to support apikey for accessing gdpr data, this was removed. This authenticates with given token.
* Use gdpr token.
[LOM-359]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-359: Add auth support for gdpr token.

- conf/cmi/block.block.hdbt_subtheme_announcements.yml
- conf/cmi/block.block.hdbt_subtheme_breadcrumbs.yml
- conf/cmi/block.block.hdbt_subtheme_heroblock.yml
- conf/cmi/block.block.hdbt_subtheme_messages.yml
* Moved around announcements and status messages
* `git checkout feature/LOM-402-lohkojen-sijoittelu`
* `make fresh`
[LOM-402]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-402: move announcements and status messages

- public/modules/custom/form_tool_webform_parameters/form_tool_webform_parameters.module
New webform default state to WIP
* `git checkout LOM-401-form-default-state`
* `make fresh`
[LOM-401]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-401: Fix new form default state to WIP

- composer.json
- composer.lock
- conf/cmi/core.extension.yml
- conf/cmi/purge_users.settings.yml
- public/modules/custom/form_tool_profile/form_tool_profile.module
Installed and configured purge module to purge endusers after 5 hours.
* `make fresh`
[LOM-386]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-386: Add and configure purge users module

- public/modules/custom/webform_formtool_handler/src/Plugin/WebformHandler/FormToolWebformHandler.php
- public/modules/custom/webform_formtool_handler/src/Service/SubmissionEmailService.php
- public/modules/custom/webform_formtool_handler/templates/submission-email-notify-submitter.html.twig
- public/modules/custom/webform_formtool_handler/templates/submission-email-notify.html.twig
- public/modules/custom/webform_formtool_handler/translations/fi/fi.po
- public/modules/custom/webform_formtool_handler/translations/sv/sv.po
- public/modules/custom/webform_formtool_handler/webform_formtool_handler.module
- public/modules/custom/webform_formtool_handler/webform_formtool_handler.services.yml
Email templates and language versions for submitter and controller
* `git checkout feature/LOM-392-email-templates`
* `make fresh`
* Make sure you have following lines in your local.settings.php, so you can use mailhog.
```
$config['smtp.settings']['smtp_host'] = "stonehenge";
$config['smtp.settings']['smtp_port'] = 1025;
```
https://mailhog.docker.so/
[LOM-392]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: LOM-392: Confirmation email templates for submitter and controller.

- composer.json
- composer.lock
- conf/cmi/core.extension.yml
- conf/cmi/disable_messages.settings.yml
Installed and configured disable_messages module.
Decided to use this module, instead of overwriting messaging service - as we would have anyone had to somehow filter out specific messages. and MessengerInterface doesn't allow some much configuration how to pass metadata.
* `git checkout LOM-395-filter-system-messages`
* `make fresh`
[LOM-395]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-395: Installed and configured disable_messages module

- public/modules/custom/form_tool_profile/form_tool_profile.module
- public/themes/custom/hdbt_subtheme/templates/navigation/links--language-block.html.twig
Alter language links to show possible node translation, instead of translation of system.403 page when accessing forms that require authentication
* `git checkout feature/LOM-420-http403-language-links`
* `make fresh`
[LOM-420]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-420: Alter language switch links on 403 pages

- public/modules/custom/form_tool_profile/form_tool_profile.services.yml
- public/modules/custom/form_tool_profile/src/EventSubscriber/RequestEventSubscriber.php
Fixes problem with the implementation. Trigger cache kill switch.
* `make fresh`
[LOM-366]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-366: Trigger cache kill switch before redirection

- conf/cmi/webform.settings.yml
* `git checkout LOM-438-remove-empty-text`
* `make fresh`
[LOM-438]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-438: Remove {empty} text from submission results

- conf/cmi/webform.webform.todistusjaljennospyynto_tilaus.yml
* Fix typo in Todistusjäljennöspyyntö
* `git checkout feature/LOM-439-kirjoitusvirhe-fix`
* `make fresh`
[LOM-439]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-439: Fix typo in Todistusjäljennöspyyntö

- composer.lock
Dev environmnemt was broken because of incorrect naming. This fixes it.
* HP module version bump.
> refactor: Update HP version

- composer.lock
GDPR api calls need to be authenticated with apikey instead of JWT token.
* ATV version update to 0.9.5
> AU-820: fix: ATV version update

- public/modules/custom/autologout_extend/js/autologout.js
- public/modules/custom/webform_formtool_handler/templates/submission-email-notify-submitter.html.twig
Add function call to check if path prefix should be added to log out url.
* `git checkout LOM-461-autologout-fix`
* `make fresh`
[LOM-461]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-461: Change logout urls to check if they need a prefixed address

- conf/cmi/language/sv/webform.webform.todistusjaljennospyynto_tilaus.yml
- conf/cmi/webform.webform.todistusjaljennospyynto_tilaus.yml
- public/modules/custom/form_tool_webform_parameters/form_tool_webform_parameters.module
* Added conditional privacy policy link
* `git checkout feature/LOM-449-privacy-policy`
* `make fresh`
[LOM-449]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-449: Added conditional privacy policy link

- conf/cmi/disable_messages.settings.yml
disable_modules is allocating too much memory, which causes PHP process to die due hitting configured max.
Configured disable_messages to skip admin/' pages.
There is a issue in d.org with reviewed status, so hopefully a fix will flow through version updates, but if this for some reason unfolds to a bigger problem, we can apply the patch manually.  https://www.drupal.org/project/disable_messages/issues/3252232 
* `git checkout feature/LOM-453-fix-admin-500-error`
* `make fresh`
[LOM-453]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-453: Configuration update to disable disable_messages on admin pages

- conf/cmi/autologout.settings.yml
- conf/cmi/language/fi/autologout.settings.yml
- conf/cmi/language/sv/autologout.settings.yml
* Change translations in autologout modal
* `git checkout feature/LOM-440-autologout-translations`
* `make fresh`
[LOM-440]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-440: autologout translations

- public/themes/custom/hdbt_subtheme/templates/misc/status-messages.html.twig
* Moved status message to status title
* Did not change the text bc it comes from helsinki profiili module
* `git checkout feature/LOM-496-status-message`
* `make fresh`
[LOM-496]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-496: re-style status message

- composer.json
- patches/core_language_manager.patch
Patch core language manager, as 9.5.9 introduced a backported change, which breaks our link alters.
* `git checkout LOM-506-language-link-visibility`
* `make fresh`
[LOM-506]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-506: Patch languagemanager as backport is breaking our link alters

- .gitignore
- test/resources/variables/lomake-Variables.robot
- test/tests/SMOKE-lomake-test-set.robot
- test/tests/lomake-Check-tjpt-page-functionality-and-check-lomake.robot
- test/tests/lomake-Check-tjpt-page-functionality-and-logout.robot
- test/tests/lomake-direct-lomake-url.robot
- test/tests/lomake-direct-url-and-content-in-mail.robot
Todistuksen antamisvuosi steps added
[LOM-511]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LOM-511: Todistuksen antamisvuosi steps added

- conf/cmi/language/sv/webform.webform.todistusjaljennospyynto_tilaus.yml
- public/modules/custom/form_tool_share/translations/sv.po
- public/modules/custom/form_tool_webform_components/form_tool_contact_info/translations/fi/fi.po
- public/modules/custom/form_tool_webform_components/form_tool_contact_info/translations/sv/sv.po
- public/modules/custom/webform_formtool_handler/src/EventSubscriber/WebformSubmissionSubscriber.php
* Swedish translations to conf files.
* `git checkout feature/LOM-523-swedish-translations`
* `make fresh`
[LOM-523]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-523: fix: LOM-523: fix missing swedish translations

- public/sites/default/development.settings.php
- public/sites/default/staging.settings.php
- public/sites/default/testing.settings.php
- scheduled-dev-env-browsers-run.yml
- scheduled-test-env-browsers-run.yml
Add email overrides for other envs, so that only production mails are sent to käsittelijät.
[LOM-527]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LOM-527: Add email overrides for form email
